[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.110.2"
python-multipart = "^0.0.9"
uvicorn = "^0.29.0"
gunicorn = "^22.0.0"
httpx = "^0.27.0"
faststream = {extras = ["rabbit"], version = "^0.5.3"}
