[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
youtube-dl = {git = "https://github.com/ytdl-org/youtube-dl.git"}
httpx = "^0.27.0"
faststream = {extras = ["rabbit"], version = "^0.5.3"}
